# Generated by Django 5.2.7 on 2025-10-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('c', 'Completed'), ('d', 'Dropped')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('s', 'Suspended'), ('g', 'Graduated'), ('w', 'Withdrawn')], default='a', max_length=1),
        ),
    ]
