# Generated by Django 5.2.7 on 2025-11-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_status_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1),
        ),
    ]
