# Generated by Django 5.2.7 on 2025-11-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_status'),
        ('students', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(through='students.Enrollment', to='courses.course'),
        ),
    ]
