# Generated by Django 5.2.7 on 2026-04-18 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_material_teacher'),
        ('students', '0006_enrollment_unique_student_course_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_course_enrollment',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('student', 'course'), name='unique_student_course_enrollment'),
        ),
    ]
