# Generated by Django 5.2.7 on 2025-11-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_submission_status_examquestions_exams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='examansweroptions',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='examanswers',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='examquestions',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='examquestionsmapping',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='examreviews',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='exams',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='examsubmissions',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='questioncategories',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='submissiongrade',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
