# Generated by Django 5.2.7 on 2025-12-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assignment_status_examansweroptions_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='examquestions',
            name='status',
        ),
        migrations.RemoveField(
            model_name='examquestionsmapping',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='status',
        ),
        migrations.RemoveField(
            model_name='questioncategories',
            name='status',
        ),
        migrations.RemoveField(
            model_name='questionoptions',
            name='status',
        ),
        migrations.RemoveField(
            model_name='submissiongrade',
            name='status',
        ),
    ]
