# Generated by Django 5.2.7 on 2026-04-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assignment_status_examansweroptions_status_and_more'),
        ('courses', '0006_alter_material_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='courses.course'),
        ),
    ]
