# Generated by Django 5.2.7 on 2026-06-01 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assignment_course'),
        ('students', '0007_remove_enrollment_unique_student_course_enrollment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examansweroptions',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='examquestionsmapping',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmissions',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='examansweroptions',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'a')), fields=('answer', 'option'), name='unique_answer_option'),
        ),
        migrations.AddConstraint(
            model_name='examquestionsmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'a')), fields=('exam', 'question'), name='unique_exam_question_mapping'),
        ),
        migrations.AddConstraint(
            model_name='examsubmissions',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'a')), fields=('exam', 'student'), name='unique_exam_student_submission'),
        ),
    ]
