# Generated by Django 5.2.7 on 2026-06-03 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_examansweroptions_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='examanswers',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'a')), fields=('exam_submission', 'question'), name='unique_active_exam_answer'),
        ),
    ]
