# Generated by Django 5.2.7 on 2026-06-22 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_exams_duration_examanswers_unique_active_exam_answer"),
        ("students", "0007_remove_enrollment_unique_student_course_enrollment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="exams",
            name="end_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="exams",
            name="start_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="examsubmissions",
            name="submission_time",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[("s", "Submitted"), ("l", "Late"), ("g", "Graded")], db_index=True, default="s", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "i"), _negated=True),
                fields=("assignment", "student"),
                name="unique_active_assignment_submission",
            ),
        ),
    ]
