from datetime import date, timedelta

from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone
from rest_framework import status
from rest_framework.test import APITestCase

from assessments.models import (
    ExamAnswerOptions,
    ExamAnswers,
    ExamQuestions,
    Exams,
    ExamSubmissions,
    QuestionCategories,
    QuestionOptions,
)
from courses.models import Course
from students.models import Student

User = get_user_model()


class ExamAnswerOptionAPITestCase(APITestCase):
    """
    Integration tests for ExamAnswerOptions.
    Validates restricted POST method, constraint safety, and reactivation logic.
    """

    def setUp(self):
        # Complex Base Setup for Exam Architecture
        self.user = User.objects.create_user(username="student_neo", password="123")
        self.student = Student.objects.create(
            user=self.user,
            first_name="Thomas",
            last_name="Anderson",
            date_of_birth="1990-03-24",
            gender="m",
            contact_number="123",
            emergency_contact_name="Morpheus",
            emergency_contact_number="911",
            status="a",
            date_joined=date.today(),
        )
        self.course = Course.objects.create(title="Matrix Protocols", status="p")
        self.exam = Exams.objects.create(
            course=self.course,
            title="Red Pill Test",
            start_time=timezone.now(),
            end_time=timezone.now() + timedelta(hours=1),
            total_marks=100,
            status="a",
        )

        self.category = QuestionCategories.objects.create(name="Logic", status="a")
        self.question = ExamQuestions.objects.create(
            category=self.category, question_text="What is the Matrix?", question_type="m", marks=10.0, status="a"
        )
        self.option_a = QuestionOptions.objects.create(
            question=self.question, option_code="A", option_text="Control", is_correct=True, status="a"
        )

        # Setup the existing Submission and Base Answer
        self.submission = ExamSubmissions.objects.create(exam=self.exam, student=self.student, status="a")
        self.answer = ExamAnswers.objects.create(exam_submission=self.submission, question=self.question, status="a")

        self.list_url = reverse("exam-answer-option-list")

    def test_create_answer_option_success(self):
        """Verify POST successfully links an option to an answer."""
        payload = {"answer": self.answer.id, "option": self.option_a.id}
        response = self.client.post(self.list_url, data=payload, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(ExamAnswerOptions.objects.count(), 1)

    def test_create_duplicate_active_option_blocked(self):
        """Verify POST blocks duplicate active selections to protect constraints."""
        ExamAnswerOptions.objects.create(answer=self.answer, option=self.option_a, status="a")

        payload = {"answer": self.answer.id, "option": self.option_a.id}
        response = self.client.post(self.list_url, data=payload, format="json")

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["detail"], "This option is already selected for this answer.")
        self.assertEqual(ExamAnswerOptions.objects.count(), 1)

    def test_reactivate_soft_deleted_option(self):
        """Verify POST reactivates a soft-deleted option instead of crashing."""
        # Pre-create an INACTIVE record
        ExamAnswerOptions.objects.create(answer=self.answer, option=self.option_a, status="i")

        payload = {"answer": self.answer.id, "option": self.option_a.id}
        response = self.client.post(self.list_url, data=payload, format="json")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        # Verify the record count didn't increase, it just updated the status
        self.assertEqual(ExamAnswerOptions.all_objects.count(), 1)
        self.assertEqual(ExamAnswerOptions.objects.get(id=response.data["id"]).status, "a")

    def test_method_not_allowed(self):
        """Verify GET is blocked on the list route, and detail routes physically do not exist."""
        opt = ExamAnswerOptions.objects.create(answer=self.answer, option=self.option_a, status="a")

        # GET on list URL should be 405 Method Not Allowed (only POST is allowed)
        self.assertEqual(self.client.get(self.list_url).status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

        # Detail URLs are not generated by the router, so manually accessing them yields 404
        manual_detail_url = f"/exam-answer-options/{opt.id}/"
        self.assertEqual(self.client.patch(manual_detail_url, {}).status_code, status.HTTP_404_NOT_FOUND)
        self.assertEqual(self.client.delete(manual_detail_url).status_code, status.HTTP_404_NOT_FOUND)

    def test_create_option_after_exam_ends_blocked(self):
        """Verify POST is blocked if the parent exam has already ended."""
        from datetime import timedelta

        from django.utils import timezone

        # Fast-forward the exam's end time to the past
        self.exam.end_time = timezone.now() - timedelta(minutes=5)
        self.exam.save()

        payload = {"answer": self.answer.id, "option": self.option_a.id}
        response = self.client.post(self.list_url, data=payload, format="json")

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["detail"], "Cannot modify answers after the exam has ended.")

    def test_create_option_on_graded_submission_blocked(self):
        """Verify POST is blocked if the parent submission is already graded."""
        # Set the parent submission status to graded
        self.submission.status = "g"
        self.submission.save()

        payload = {"answer": self.answer.id, "option": self.option_a.id}
        response = self.client.post(self.list_url, data=payload, format="json")

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertEqual(response.data["detail"], "Cannot modify answers for a graded submission.")
