# Generated by Django 5.2.7 on 2026-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_alter_teacher_gender_alter_teacher_status_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('l', 'On Leave'), ('r', 'Resigned'), ('t', 'Retired')], default='a', max_length=20),
        ),
    ]
