# Generated by Django 5.2.7 on 2026-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_migrate_teacher_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('l', 'On Leave'), ('r', 'Resigned'), ('t', 'Retired')], default='a', max_length=1),
        ),
    ]
