# Generated by Django 5.2.7 on 2026-04-30 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_alter_teacher_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email_institutional',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('employee_code',), name='unique_active_employee_code'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('email_institutional',), name='unique_active_email_institutional'),
        ),
    ]
