# Generated by Django 5.2.7 on 2026-04-30 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_alter_teacher_email_institutional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='staffs_teac_status_5dc79f_idx'),
        ),
        migrations.AddIndex(
            model_name='userdepartment',
            index=models.Index(fields=['user', 'status'], name='staffs_user_user_id_235cea_idx'),
        ),
        migrations.AddIndex(
            model_name='userdesignation',
            index=models.Index(fields=['user', 'status'], name='staffs_user_user_id_d235a0_idx'),
        ),
        migrations.AddIndex(
            model_name='userqualification',
            index=models.Index(fields=['user', 'status'], name='staffs_user_user_id_461d32_idx'),
        ),
        migrations.AddIndex(
            model_name='userspecialization',
            index=models.Index(fields=['user', 'status'], name='staffs_user_user_id_1d3823_idx'),
        ),
    ]
