# Generated by Django 5.2.7 on 2026-04-30 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_teacher_staffs_teac_status_5dc79f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userdepartment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('user', 'department'), name='unique_active_user_department'),
        ),
        migrations.AddConstraint(
            model_name='userdesignation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('user', 'designation'), name='unique_active_user_designation'),
        ),
        migrations.AddConstraint(
            model_name='userqualification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('user', 'qualification'), name='unique_active_user_qualification'),
        ),
        migrations.AddConstraint(
            model_name='userspecialization',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('user', 'specialization'), name='unique_active_user_specialization'),
        ),
    ]
