# Generated by Django 5.2.7 on 2026-05-02 14:58

from django.conf import settings
from django.db import migrations, models

def resolve_user_teacher_duplicates(apps, schema_editor):
    # Ensures each user has only one non-inactive Teacher profile before enforcing the UniqueConstraint.
    Teacher = apps.get_model('staffs', 'Teacher')
    from django.db.models import Count

    # Find users who have more than one profile that is NOT inactive(i)
    duplicate_users = (
        Teacher.objects.exclude(status='i')
        .values('user')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .values_list('user', flat=True)
    )

    for user_id in duplicate_users:
        # Fetch all non-inactive profiles for this user, newest first
        teachers = Teacher.objects.filter(user_id=user_id).exclude(status='i').order_by('-id')

        # Keep the newest profile [0] active, mark the rest as inactive
        for duplicate in teachers[1:]:
            duplicate.status = 'i'
            duplicate.save(update_fields=['status'])
    

class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_userdepartment_unique_active_user_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(resolve_user_teacher_duplicates, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('user',), name='unique_active_teacher_user'),
        ),
    ]
