# Generated by Django 5.2.7 on 2025-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseteachers_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('a', 'Archived')], default='d', max_length=1),
        ),
    ]
