# Generated by Django 5.2.7 on 2025-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='publish_status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('a', 'Archived')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
