# Generated by Django 5.2.7 on 2025-12-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_publish_status_alter_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='publish_status',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('a', 'Archived')], default='d', max_length=1),
        ),
    ]
