# Generated by Django 5.2.7 on 2026-04-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_publish_status_alter_course_status'),
        ('staffs', '0002_alter_teacher_gender_alter_teacher_status_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to='staffs.teacher'),
        ),
    ]
