# Generated by Django 5.2.7 on 2026-04-20 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_material_teacher'),
        ('staffs', '0004_migrate_teacher_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseteachers',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'i'), _negated=True), fields=('course', 'teacher'), name='unique_active_course_teacher'),
        ),
    ]
