# Generated by Django 5.2.7 on 2025-11-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='chatresponse',
            name='status',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
